### ISSUE TITLE
Cargo build-bpf doesnt compile due to openssl issue

### ISSUE THREAD

**Issue by anoushk1234** [Unboxed-Software/solana-course#129]
```
BPF SDK: /home/ubuntu/.local/share/solana/install/releases/1.10.31/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
/home/ubuntu/.rustup/toolchains/bpf/bin/cargo: /lib/x86_64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/ubuntu/.rustup/toolchains/bpf/bin/cargo)
/home/ubuntu/.rustup/toolchains/bpf/bin/cargo: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /home/ubuntu/.rustup/toolchains/bpf/bin/cargo)
```
Trying https://soldev.app/course/local-setup in ec2 instance ubuntu instance and i get this error

**Comment by anoushk1234** [comment]
This might be because libssl.so.1.1 is deprecated in ubuntu 22 so might be a good idea to mention that

**Comment by mikemaccana** [comment]
This issue is nearly a couple of years out date, and doesn't seem to be happening on Ubuntu anymore (see https://github.com/solana-developers/professional-education/actions/runs/8899038259/job/24437460145 for an Ubuntu run, that passes, no libssl fixes needed). I'm going to close, please reopen if something else needs doing.
