### ISSUE TITLE
Adding support for other sol wallets

### ISSUE THREAD

**Issue by hydrogenbond007** [Unboxed-Software/solana-course#146]
We can only connect a phantom wallet right now, and I don't use a phantom lol.
Its quite easy to add support for most of the commonly used wallets like solflare and others, just need to add a few lines to the frontend. Will change it in a PR if you like

**Comment by hydrogenbond007** [comment]
@jamesrp13 any updates?

**Comment by jamesrp13** [comment]
@hydrogenbond007 please be patient we have a lot of things in the air right now.

As for your question, the "Interacting with wallets" lesson does mention that the process you use for Phantom is the same for other wallets using wallet adapter. See the attached image.  
<img width="902" alt="Screen Shot 2022-08-24 at 1 38 27 PM" src="https://user-images.githubusercontent.com/11344110/186508304-7cade744-0ec2-47cf-a79d-da3f74c43494.png">

We aren't going to show all of them but you can just as easily add `solana/wallet-adapter-solflare` instead of phantom or other wallets supported by wallet adapter. The README on the wallet adapter repo provides a list of all of the supported wallets. https://github.com/solana-labs/wallet-adapter 

We show the pattern and how to use wallet adapter and then you can take it from there and incorporate whatever wallet you use.
