### ISSUE TITLE
Transactions should wait till confirmation before resolving.

### ISSUE THREAD

**Issue by BrainyZombie** [Unboxed-Software/solana-course#240]
Newer Solana API versions don't wait till a transaction is confirmed by the cluster before resolving their promises.

The sample solutions provided work due to being on older API versions, but someone following along the course on their may face subsequent transactions failing when they depend on confirmation of the previous transactions.

Module 2-1 for example, throws TokenAccountNotFoundError when run with the latest APIs. Further modules may do so too though I haven't reached them yet.

The connections being created should make sure they're configured to wait till confirmation.

**Comment by mikemaccana** [comment]
Hey @BrainyZombie! I missed your more recent updates after I closed the issue. 

As you say, this sounds like an issue in web3.js - I'm going to try https://codesandbox.io/p/devbox/solana-reproduction-4h6skq now on a current web3.js and then go from there.

**Comment by mikemaccana** [comment]
I've checked https://codesandbox.io/p/devbox/solana-reproduction-4h6skq?file=%2Fsrc%2Findex.ts%3A1%2C1-40%2C1 and it returns 100% of the time without `confirmed`.

I've also cleaned up the code and ran it myself, and it returns 100% of the time without `confirmed`. 

I do think you may have found an issue, but it's been fixed in the the current `@solana/web3.js@1.95.2`
